auth_enabled: false

server:
  log_level: info
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857608
  grpc_server_max_concurrent_streams: 1000

distributor:
  ring:
    kvstore:
      store: memberlist

ingester_client:
  grpc_client_config:
    max_send_msg_size: 104857600

ingester:
  max_transfer_retries: 0
  chunk_target_size: 1536000
  chunk_encoding: snappy
  lifecycler:
    ring:
      kvstore:
        store: memberlist

memberlist:
  join_members:
    - {{ include "loki.fullname" . }}-memberlist

limits_config:
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_concurrent_tail_requests: 20
  max_cache_freshness_per_query: 10m

schema_config:
  configs:
    - from: 2020-09-07
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  aws:
    # The period behind the domain forces the S3 library to use it as a host name, not as an AWS region.
    s3: http://minio.minio.svc.cluster.local.:9000/loki
    s3forcepathstyle: true
  boltdb_shipper:
    active_index_directory: /var/loki/index
    shared_store: s3
    cache_location: /var/loki/cache
    cache_ttl: 168h
  index_queries_cache_config:
    memcached:
      batch_size: 100
      parallelism: 100
    memcached_client:
      consistent_hash: true
      host: {{ include "loki.memcachedIndexQueriesFullname" . }}
      service: http

chunk_store_config:
  max_look_back_period: 0s
  chunk_cache_config:
    memcached:
      batch_size: 100
      parallelism: 100
    memcached_client:
      consistent_hash: true
      host: {{ include "loki.memcachedChunksFullname" . }}
      service: http

querier:
  query_ingesters_within: 2h

query_range:
  # make queries more cache-able by aligning them with their step intervals
  align_queries_with_step: true
  max_retries: 5
  # parallelize queries in 15min intervals
  split_queries_by_interval: 15m
  cache_results: true
  results_cache:
    cache:
      memcached_client:
        consistent_hash: true
        host: {{ include "loki.memcachedFrontendFullname" . }}
        max_idle_conns: 16
        service: http
        timeout: 500ms
        update_interval: 1m

frontend_worker:
  frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095
  grpc_client_config:
    max_send_msg_size: 104857600

frontend:
  log_queries_longer_than: 5s
  compress_responses: true

compactor:
  shared_store: s3

ruler:
  storage:
    type: local
    local:
      directory: /etc/loki/rules
  ring:
    kvstore:
      store: memberlist
  rule_path: /var/loki/scratch
  alertmanager_url: http://alertmanager-operated.monitoring.svc.cluster.local:9093
  enable_alertmanager_v2: true
  enable_api: true
  enable_sharding: true
