fullnameOverride: loki
nameOverride: loki

loki:
  revisionHistoryLimit: 1

serviceAccount:
  enabled: true

serviceMonitor:
  enabled: true

prometheusRule:
  enabled: true
  groups:
    - name: loki-rules
      rules:
        - record: job:loki_request_duration_seconds_bucket:sum_rate
          expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job)
        - record: job_route:loki_request_duration_seconds_bucket:sum_rate
          expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job, route)

gateway:
  replicas: 2

distributor:
  replicas: 3

ingester:
  replicas: 3
  extraEnvFrom:
    - secretRef:
        name: minio-credentials
  persistence:
    enabled: true

querier:
  replicas: 3
  extraEnvFrom:
    - secretRef:
        name: minio-credentials
  persistence:
    enabled: true

queryFrontend:
  replicas: 2

compactor:
  enabled: true
  extraEnvFrom:
    - secretRef:
        name: minio-credentials
  persistence:
    enabled: true

ruler:
  enabled: true
  replicas: 2
  extraEnvFrom:
    - secretRef:
        name: minio-credentials
  directories:
    fake:
      rules.txt: |
        groups:
          - name: should_fire
            rules:
              - alert: HighPercentageError
                expr: |
                  sum(rate({app="loki"} |= "error" [5m])) by (job)
                    /
                  sum(rate({app="loki"}[5m])) by (job)
                    > 0.05
                for: 10m
                labels:
                  severity: warning
                annotations:
                  summary: High error percentage

memcachedExporter:
  enabled: true

memcachedChunks:
  enabled: true
  replicas: 2

memcachedFrontend:
  enabled: true
  replicas: 2

memcachedIndexQueries:
  enabled: true
  replicas: 2

