apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eventrouter.fullname" . }}
  labels:
    {{- include "eventrouter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "eventrouter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "eventrouter.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "eventrouter.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: eventrouter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /etc/eventrouter
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "eventrouter.fullname" . }}
