{
 "title": "Loki Canary",
 "description": "Loki Canary is a standalone app that audits the log capturing performance of Loki.",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{namespace=\"$namespace\",pod=~\"loki-canary-.*\"}, pod)"
   },
   { "name": "namespace", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Total entries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(loki_canary_entries_total{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total entries rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_entries_total{pod=~\"$pod\"}[30m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Missing entries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(loki_canary_missing_entries_total{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Missing entries rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_missing_entries_total{pod=~\"$pod\"}[30m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Websocket missing entries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(loki_canary_websocket_missing_entries_total{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Websocket missing entries rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_websocket_missing_entries_total{pod=~\"$pod\"}[30m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Spot check entries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(loki_canary_spot_check_entries_total{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Spot check entries rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_spot_check_entries_total{pod=~\"$pod\"}[30m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Spot check missing entries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(loki_canary_spot_check_missing_entries_total{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Spot check missing entries rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_spot_check_missing_entries_total{pod=~\"$pod\"}[30m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Unexpected entries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(loki_canary_unexpected_entries_total{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Unexpected entries rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_unexpected_entries_total{pod=~\"$pod\"}[30m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Duplicate entries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(loki_canary_duplicate_entries_total{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Duplicate entries rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_duplicate_entries_total{pod=~\"$pod\"}[30m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Out of order entries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_canary_out_of_order_entries_total{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Out of order entries rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_out_of_order_entries_total{pod=~\"$pod\"}[30m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Websocket pings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(loki_canary_ws_pings_total{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Websocket ping rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_ws_pings_total{pod=~\"$pod\"}[30m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Websocket reconnects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(loki_canary_ws_reconnects_total{pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Websocket reconnect rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(loki_canary_ws_reconnects_total{pod=~\"$pod\"}[30m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Metric test deviation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(sum(loki_canary_metric_test_expected{pod=~\"$pod\"}) - sum(loki_canary_metric_test_actual{pod=~\"$pod\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Metric test",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(loki_canary_metric_test_actual{pod=~\"$pod\"})",
     "legendFormat": "Actual"
    },
    {
     "expr": "sum(loki_canary_metric_test_expected{pod=~\"$pod\"})",
     "legendFormat": "Expected"
    }
   ]
  },
  {
   "title": "Response latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_canary_response_latency_seconds_bucket{pod=~\"$pod\"}[5m])) by (le)) ",
     "legendFormat": ".50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_canary_response_latency_seconds_bucket{pod=~\"$pod\"}[5m])) by (le)) ",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_canary_response_latency_seconds_bucket{pod=~\"$pod\"}[5m])) by (le)) ",
     "legendFormat": ".99"
    }
   ]
  },
  {
   "title": "Spot check latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_canary_spot_check_request_duration_seconds_bucket{pod=~\"$pod\"}[5m])) by (le)) ",
     "legendFormat": ".50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_canary_spot_check_request_duration_seconds_bucket{pod=~\"$pod\"}[5m])) by (le)) ",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_canary_spot_check_request_duration_seconds_bucket{pod=~\"$pod\"}[5m])) by (le)) ",
     "legendFormat": ".99"
    }
   ]
  },
  {
   "title": "Metric test latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_canary_metric_test_request_duration_seconds_bucket{pod=~\"$pod\"}[5m])) by (le)) ",
     "legendFormat": ".50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_canary_metric_test_request_duration_seconds_bucket{pod=~\"$pod\"}[5m])) by (le)) ",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_canary_metric_test_request_duration_seconds_bucket{pod=~\"$pod\"}[5m])) by (le)) ",
     "legendFormat": ".99"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{app=\"loki-canary\",pod=~\"$pod\"} != \"ppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\""
    }
   ]
  }
 ]
}