existingSecret: minio-credentials

defaultBucket:
  enabled: true
  name: loki

DeploymentUpdate:
  type: Recreate

persistence:
  size: 1Gi

resources: {}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - localhost
