apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "test-logger.fullname" . }}
  labels:
    {{- include "test-logger.labels" . | nindent 4 }}
data:
  log.sh: |
    {{- .Files.Get "scripts/log.sh" | nindent 4 }}
