apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-logger.fullname" . }}
  labels:
    {{- include "test-logger.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "test-logger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "test-logger.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "test-logger.fullname" . }}
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: test-logger
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /scripts/log.sh
          args:
            - {{ .Values.logType }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: {{ include "test-logger.fullname" . }}
            defaultMode: 0755
