apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "test-logger.fullname" . }}
  labels:
    {{- include "test-logger.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
